### ISSUE TITLE
problem unzipping (release  v0.19.2)

### ISSUE THREAD

**Issue by jcd000** [Falconne/AvoidFriendlyFire#6]
On linux.
Unzipping via gui (engrampa) fails with some errors of type: "ERROR: Can not open output file : Invalid argument : /path/to/folder/AvoidFriendlyFire\About\Version.xml"

Unzipping via command line "unzip" package works but gives:
"warning:  AvoidFriendlyFire.0.19.2.0.zip appears to use backslashes as path separators"

So maybe backslashes as path separators should be avoided for file names?

**Comment by Falconne** [comment]
Thanks, will take a look. I'm using PowerShell to create the zip and that must be using forward slashes.

**Comment by Falconne** [comment]
Should be fixed now
